controller_manager:
  ros__parameters:
    update_rate: 1000
    #use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster


joint_broad:
  ros__parameters:
    joints: ['Mecanum_roller_joint_1', 'Mecanum_roller_joint_2', 'Mecanum_roller_joint_3', 'Mecanum_roller_joint_4', 'Mecanum_roller_joint_5', 'Mecanum_roller_joint_6', 'Mecanum_roller_joint_7', 'Mecanum_roller_joint_8', 'Mecanum_roller_joint_9']