<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

	<!--lidar intrinsics-->
	<link name="lidar_link">
		<inertial>
			<origin xyz = "0 0 0" rpy="0 0 0"/>
			<mass value=".17"/>
			<inertia ixx="0.001"  ixy="0"  ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
		</inertial>

		<collision>
			<origin xyz = "0 0 0"/>
			<geometry>
				<cylinder radius="${lidar_radius}" length=".06"/>
			</geometry>
		</collision>

		<visual>
			<origin xyz = "0 0 0" rpy="0 0 0"/>
			<geometry>
				<cylinder radius="${lidar_radius}" length=".06"/>
			</geometry>
			<material name="black">
				<color rgba="0 0 0 1"/>
			</material>
		</visual>
	</link>

	<!--create the joint that the lidar_link will be bound to with the base being the base_link-->
	<joint name="lidar_joint" type="fixed"> 
	<!--^^make joint continuous to mimic spinning lidar?-->
		<parent link="chassis"/>
		<child link="lidar_link"/>
		<origin xyz="${lidar_radius} 0 ${chassis_height + 0.03}" rpy="0 0 0"/>
	</joint>
	
	<!--adding gazebo plugins to the sim-->
	<gazebo reference="lidar_link">
    	<material>Gazebo/Black</material>
		<sensor name="lidar" type="ray">
			<always_on>true</always_on>
			<visualize>true</visualize>
			<update_rate>5</update_rate>
			<ray>
				<scan>
					<horizontal>
						<samples>8000</samples>
						<resolution>1</resolution>
						<!--min and max angles are in radians-->
						<min_angle>0.0</min_angle>
						<max_angle>6.28</max_angle>
					</horizontal>
				</scan>
				<range>
					<min>0.12</min>
					<max>4</max>
					<resolution>1</resolution>
				</range>
				<noise>
					<type>gaussian</type>
					<mean>0.0</mean>
					<stddev>0.01</stddev>
				</noise>
			</ray>
			<plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
				<ros>
					<remapping>~/out:=scan</remapping>
				</ros>
				<output_type>sensor_msgs/LaserScan</output_type>
				<frame_name>lidar_link</frame_name>
			</plugin>
		</sensor>
	</gazebo>
</robot>
